--create schema userb;
--
--CREATE TABLE userb
--(
-- name varchar(100) NOT NULL,
--  userId varchar(11) NOT NULL ,
-- username varchar(100) DEFAULT NULL,
-- password varchar(100) DEFAULT NULL,
-- PRIMARY KEY (userId)
--);
--
--CREATE TABLE user_bro
--(
-- name varchar(100) NOT NULL,
--  userId varchar(11) NOT NULL ,
-- username varchar(100) DEFAULT NULL,
-- password varchar(100) DEFAULT NULL,
-- PRIMARY KEY (userId)
--);
--
--CREATE TABLE user_bro
--(
-- name varchar(100) NOT NULL,
--  userId varchar(11) NOT NULL ,
-- username varchar(100) DEFAULT NULL,
-- password varchar(100) DEFAULT NULL,
-- PRIMARY KEY (userId)
--);